name: Lint

on: push

jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.x
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
